### PR TITLE
compatible with php 8.0

### PR DESCRIPTION
**Pull request by juizmill**
This pull request is for an issue #14

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | yes

### CODE REVIEW

**Comment by samsonasik** [comment]
Coverage seems not generated, as it seems uses Xdebug 3 at https://travis-ci.com/github/laminas/laminas-console/jobs/472135358

```bash
$ if [[ $TEST_COVERAGE == 'true' ]]; then vendor/bin/php-coveralls -v ; fi

In Configurator.php line 152:

                                                                                                   
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                    

  coverage_clover XML file is not readable: /home/travis/build/laminas/laminas-console/clover.xml  
 ```
  
 The warning is on phpunit run itself:
 
 ```bash
 Runtime:       PHP 7.3.26

Configuration: /home/travis/build/laminas/laminas-console/phpunit.xml.dist

Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set
``` 
  
 You may need to add  :
 
 ```yml
 env:
  - XDEBUG_MODE=coverage
 ```
 
 to travis.yml to make it works.

**Comment by juizmill** [comment]
No test case was removed because it fell 0.08%

**Comment by boesing** [comment]
@juizmill Sadly, I've created #13  and #14  even tho, this package was long time unmaintained.
I've failed on that.

So this package will not receive any further updates as it is superseded by https://docs.laminas.dev/laminas-cli/
If you are using this package, we highly encourage you to migrate to that package.

Sorry if this made you wasting your time.

**Comment by froschdesign** [comment]
Reference:

* https://github.com/laminas/laminas-console#deprecated
* https://docs.laminas.dev/laminas-console/
* https://docs.laminas.dev/components/#deprecated-packages

**Pull request closed without merging**
